### ISSUE TITLE
Mathjax

### ISSUE THREAD

**Issue by Carreau** [jsvine/nbpreview#2]
Your readme says : 

NBPreview currently doesn't support MathJax. Implementation suggestions welcome. (Markdown-parsing was interfering with prior attempts.)

Is there anything we can do on IPython side so that you can re-use our math-extraction/markdown-rendering/math-reinsertion/matjax-calling ?

**Comment by jsvine** [comment]
Great question. I'm sure it's possible, but I haven't yet figured out how to do it. 

Right now, NBPreview uses [marked](https://github.com/chjj/marked). I've been looking for other Markdown renderers that might work better with Mathjax. Do you know of any?

**Comment by Carreau** [comment]
Well, we use [marked also](https://github.com/ipython/ipython/blob/master/IPython/html/static/notebook/js/textcell.js#L266-L300)  wrapped in some utils to deals with math. We can put that in a separate utils file, so that you can just slurm that in here. 

Would that help ?

**Comment by jsvine** [comment]
That would be **incredibly** helpful :tada:

**Comment by Carreau** [comment]
Cross ref https://github.com/ipython/ipython/issues/8163 then.

**Comment by mrueegg** [comment]
Hi, I would be also very interested to get MathJax to work with this library. Is there a feature branch with your attempts to get it to work which I could have a look at? Is there anything else where I could help to make this work?

**Comment by jsvine** [comment]
Hi Michael, and thanks. I agree: It'd be a great feature. I don't have a branch with failed attempts, unfortunately; none got very far. I would, however, absolutely welcome PRs adding MathJax support. I've created a branch that can host future/ongoing attempts: https://github.com/jsvine/nbpreview/tree/mathjax-support

**Comment by mrueegg** [comment]
@jsvine Perfect, thanks. I'll let you know when I have achieved something to share.

**Comment by jsvine** [comment]
Via `notebook.js`'s addition of KaTeX support, `nbpreview` now supports math typesetting.
