### ISSUE TITLE
Nbpreview doesn't handle markdown quotes

### ISSUE THREAD

**Issue by ingodahn** [jsvine/nbpreview#5]
This is how the attached notebook looks in CoCalc (markdown quote is shown as html blockquote):
![image](https://user-images.githubusercontent.com/3258024/104589778-acc44c80-566a-11eb-83d3-01753f33b1cd.png)
And this is how it looks in the hosted version of nbpreview:
![image](https://user-images.githubusercontent.com/3258024/104589887-d3828300-566a-11eb-96e2-c5c64ce2f085.png)

[Test1.zip](https://github.com/jsvine/nbpreview/files/5814350/Test1.zip)

**Comment by jsvine** [comment]
Thank you, this is a good catch @ingodahn! This might be a side-effect of my attempt to fix the KaTeX rendering discussed in https://github.com/jsvine/nbpreview/issues/3 — or perhaps an unrelated bug I have introduced. I'll look into it.

**Comment by jsvine** [comment]
This was, indeed, a side-effect of the previous change. (A result of `>`s getting converted into `&gt;`s.) Fixed in https://github.com/jsvine/notebookjs/commit/393943f6eb27c5c0cba587e7da0485bc7c7d2cba and should be working in the hosted version of nbpreview now too.
